local L = LibStub("AceLocale-3.0"):NewLocale("GearHelper", "deDE")
if not L then
	return
end

L["merci"] = "|cFF00FF00Thank you Salty, gOOvER and RicoSoft for the translations"

L["local"] = "DE"

L["ActivatedGreen"] = "|cFF00FF00Aktiviert|r"
L["Addon"] = "GearHelper : |r"
L["ask1"] = "|cFFFFFF00Du kannst ["
L["ask2"] = "|cFFFFFF00] fragen, ob er es braucht"
L["autoEquipLootedStuff"] = "Geplünderte Gegenstände automatisch anlegen"
L["autoEquipSpecChangedStuff"] = "Auto-Ausrüsten beim Ändern der Spezialisierung"
L["autoGreed"] = "Auto-Gier"
L["autoNeed"] = "Auto-Bedarf"
L["AutoRepair"] = "Repariere automatisch"
L["auto-repair"] = "Auto-Reparatur"
L["auto-repairDesc"] = "Aktiviere / deaktiviere automatische Reparatur"
L["betterThanNothing"] = "Der Gegenstand ist besser als nichts"
L["CantRepair"] = "Du kannst nicht reparieren"
L["checkGHAutoTell"] = "Aktiviere / deaktiviere Auto-Ankündigung im Raid"
L["customWeights"] = "Eigene Gewichtung"
L["DeactivatedRed"] = "|cFFFF0000Deaktiviert|r"
L["demande1"] = "Willst Du "
L["demande2"] = "fragen, ob er es benötigt"
L["DNR"] = "Nicht automatisch reparieren"
L["dot"] = "."
L["DropBy"] = "Geplündert von:"
L["DropRate"] = "Plündechance:"
L["DropZone"] = "Zone:"
L["enable"] = "Aktiviere"
L["equipVerbose"] = "wurde soeben von GH ausgerüstet"
L["gearOptions"] = "Optionen Ausrüstung"
L["getLoot"] = "erhält"
L["gold"] = "g"
L["GuildAutoRepair"] = "Repariere mit Gildengold"
L["guildRepairCost"] = "Guilden-Reparatur Kosten:"
L["ilvlInspect"] = "Durchschnittliches ilvl:"
L["iNeededOn"] = "Ich habe Bedarf auf"
L["InviteMessage"] = "Flüster-Nachricht für eine automatische Einladung ist:"
L["isAlive"] = "lebt!"
L["isDead"] = "ist tot!"
L["itemBetterThan"] = "|cFF7FFFD4Dieser Gegenstand ist besser als dein"
L["itemBetterThan2"] = "mit einem Wert von +"
L["itemBetterThanGeneral"] = "|cFF7FFFD4Dieser Gegenstand ist besser als deiner mit einem Wert von +"
L["itemEgal"] = "Dieser Gegenstand ist gleich gut wie dein aktueller"
L["itemEgala"] = "Dieser Gegenstand ist gleich gut wie"
L["itemEgalMainD"] = "Dieser Gegenstand ist gleich gut wie deine Haupthand"
L["itemEgalMainG"] = "Dieser Gegenstand ist gleich gut wie deine Nebenhand"
L["itemEquipped"] = "Ist aktuell ausgerüstet."
L["itemLessThan"] = "|cFFFF0066Dieser Gegenstand ist schlechter als dein"
L["itemLessThanGeneral"] = "|cFFFF0066Dieser Gegenstand ist schlechter als deiner"
L["lfrCheckButtonText"] = "Rdy-Check automatisch akzeptieren"
L["lfrCheckButtonTooltip"] = "Aktiviere diese Box, um Bereitschafts-Checks im LFR automatisch zu akzeptieren."
L["local"] = "DE"
L["lootInRaidAlert"] = "Warne, wenn etwas besser ist"
L["mainD"] = "Haupthand"
L["mainG"] = "Nebenhand"
L["maj1"] = "Du benutzt Version |cFFFF0000"
L["maj2"] = "|r von GearHelper. Version |cFF00FF00"
L["maj3"] = "|r wurde gefunden bei"
L["maLangue"] = "deutsch"
L["maLanguedeDE"] = "Deutsch"
L["maLangueenUS"] = "German"
L["maLangueesES"] = "Alemán"
L["maLangueesEX"] = "Alemán"
L["maLanguefrFR"] = "Allemand"
L["maLangueitIT"] = "Tedesco"
L["maLanguekoKR"] = "독일의"
L["maLangueptBR"] = "Alemão"
L["maLangueruRU"] = "немецкий"
L["maLanguezhCN"] = "德国"
L["maLanguezhTW"] = "德國"
L["merci"] = "Author Marsgames - Temple Noir & Tempaxe - Temple Noir. Special thanks for Nirek for his amazing work."
L["miscOptions"] = "Verschiedene Optionen"
L["MmTtClickLock"] = "Umschalt + Klick, um das Minimap Icon zu  |cFFFF0000sperren|cFFFFFF00"
L["MmTtClickUnlock"] = "Umschalt + Klick, um das Minimap Icon zu  |cFFFF0000entsperren|cFFFFFF00"
L["MmTtCtrlClick"] = "Strg + Klick, um das Minimap Icon zu  |cFFFF0000verstecken|cFFFFFF00"
L["MmTtLClick"] = "Links-Klick zum Öffnen der Optionen"
L["MmTtRClickActivate"] = "Rechts-Klick zum Einschalten von GearHelper"
L["MmTtRClickDeactivate"] = "Rechts-Klick zum Ausschalten von GearHelper"
L["moneyEarned"] = "Geld verdient durch Verkauf:"
L["no"] = "Nein"
L["noxxicWeights"] = "Noxxic-Gewichtungen"
L["questRewars"] = "Auto-Akzeptieren von Quest-Belohnungen"
L["remove"] = "Entferne"
L["repairCost"] = "Reparaturkosten:"
L["sellGrey"] = "Verkaufe graue Gegenstände"
L["slashCommandConfig"] = "config - Öffne Konfiguration"
L["slashCommandCw"] = "cw - Öffne eigenes Gewichtungs-Fenster"
L["slashCommandVersion"] = "version - Zeige Addon-Version"
L["UIautoInvite"] = "Einladung durch Flüstern"
L["UIBossesKilled"] = "Bosse getötet"
L["UIBossesKilledDesc"] = "Zeige getötete Bosse im LFG Fenster"
L["UICWasPercentage"] = "Wert in Prozent"
L["UICWasPercentageDescription"] = "Beschreibt die Bedeutung jeder Statistik durch einen Prozentwert, die Summe der Werte muss 100 ergeben."
L["UIcwGemSocketCompute"] = "Berücksichtige leere Sockets in der Berechnung"
L["UIcwIlvlOption"] = "Berücksitige iLvl in der Berechnung"
L["UIcwIlvlWeight"] = "iLvl Gewichtung"
L["UIcwTemplateToUse"] = "Zu verwendende Vorlage"
L["UIGHCheckBoxAddon"] = "Schalte GearHelper ein/aus"
L["UIGHCheckBoxAutoAcceptQuestReward"] = "Schalte automatisches Akzeptieren von Questbelohnungen ein/aus"
L["UIGHCheckBoxAutoEquipLootedStuff"] = "Schalte automatisches Ausrüsten geplündeter Gegenstände ein/aus"
L["UIGHCheckBoxAutoEquipWhenSwitchSpe"] = "Aktiviere / deaktiviere automatisches Ausrüsten beim Wechseln der Spezialisierung"
L["UIGHCheckBoxAutoGreed"] = "Schalte automatisches Würfeln von Gier in Instanzen ein/aus"
L["UIGHCheckBoxAutoInvite"] = "Automatisches Einladen der Person, welche dir den text zuflüstert |cFF00FF00"
L["UIGHCheckBoxAutoNeed"] = "Schalte automatisches Würfeln von Bedarf in Instanzen ein/aus"
L["UIGHCheckBoxlootInRaidAlert"] = "Schalte die option ein/aus, um darüber informiert zu werden, wenn jemand eine bessere Ausrüstung als deine aktuelle plündert."
L["UIGHCheckBoxSellGrey"] = "Schalte automatisches Verkaufen von grauen Gegenständen ein/aus"
L["UIGlobalComputeNotEquippable"] = "Zeige nicht-ausrüstbare Gegenstände"
L["UIGlobalComputeNotEquippableDescription"] = 'Zeige "Dieser Gegenstand ist schlechter als deiner" bei nicht-ausgerüsteten Gegenständen.'
L["UIIlvlCharFrame"] = "ilvl Charakter Fenster"
L["UIIlvlCharFrameDesc"] = "Zeige das ilvl deiner Gegenstände im Charakter-Fenster"
L["UIIlvlInspectFrame"] = "ilvl beim Betrachten"
L["UIIlvlInspectFrameDesc"] = "Zeige das ilvl deines Ziels"
L["UIinviteMessage"] = "Einlade-Nachricht"
L["UIinviteMessageDesc"] = "Einlade-Nachricht, die dir gesendet werden muss, um eingeladen zu werden"
L["UIMinimapIcon"] = "Minimap Symbol"
L["UIMinimapIconDesc"] = "Zeige das Minimap-Symbol"
L["UIMyNames"] = "Namen"
L["UIMyNamesDesc"] = "Namen für die Warnungen. Getrennt durch Kommas (keine Leerzeichen)"
L["UIprintWhenEquip"] = "Meldung bei Auto-Ausrüsten"
L["UISayMyName"] = "Namenswarnung"
L["UISayMyNameDesc"] = "Zeige eine Warnung mit Ton, wenn jemand deinen Namen schreibt"
L["UIstatsTemplateToUse"] = "Zu verwendende Statistik-Vorlage"
L["UItemplateName"] = "Neue Vorlage"
L["UIWhisperAlert"] = "Flüster-Alarm"
L["UIWhisperAlertDesc"] = "Spiele einen Ton, wenn du angeflüstert wirst."
L["yes"] = "Ja"

-------------------------- CE QUI EST EN DESSOUS DE CETTE LIGNE N'EST PAS DISPO SUR CURSE ----------------------------

------------------------------------------------ SUPRIMER CETTE LIGNE ------------------------------------------------
-----

L["Tooltip"] = {
	Stat = {
		["Intellect"] = ITEM_MOD_INTELLECT_SHORT,
		["Haste"] = ITEM_MOD_HASTE_RATING_SHORT,
		["CriticalStrike"] = ITEM_MOD_CRIT_RATING_SHORT,
		["Versatility"] = ITEM_MOD_VERSATILITY,
		["Mastery"] = ITEM_MOD_MASTERY_RATING_SHORT,
		["Agility"] = ITEM_MOD_AGILITY_SHORT,
		["Stamina"] = ITEM_MOD_STAMINA_SHORT,
		["Strength"] = ITEM_MOD_STRENGTH_SHORT,
		["Armor"] = RESISTANCE0_NAME,
		["Multistrike"] = ITEM_MOD_CR_MULTISTRIKE_SHORT,
		["DPS"] = ITEM_MOD_DAMAGE_PER_SECOND_SHORT,
		["Leech"] = "Lebensraub",
		["Avoidance"] = "Vermeidung",
		["MovementSpeed"] = "Bewegungsgeschwindigkeit"
	},
	["ItemLevel"] = "^Gegenstandsstufe",
	["LevelRequired"] = "^Benötigt Stufe",
	["GemSocketEmpty"] = "Sockel",
	["BonusGem"] = "^Sockelbonus"
	--["MainDroite"] = "Dégâts main droite",
	--["MainGauche"] = "Dégâts main gauche"
}
