local L = LibStub("AceLocale-3.0"):NewLocale("GearHelper", "deDE")
if not L then
    return
end

L["merci"] = "|cFF00FF00Thank you deathcore001 and CeloSG for German translation"
L["local"] = "DE"

-------------------------- CE QUI EST EN DESSOUS DE CETTE LIGNE EST DISPO SUR CURSE --------------------------
L["ActivatedGreen"] = "|cFF00FF00Aktiviert|r"
L["Addon"] = "|cFF00FF00GearHelper: |r"
L["ask1"] = "|cFFFFFF00Du kannst ["
L["ask2"] = "|cFFFFFF00] fragen, ob er es braucht"
L["autoEquipLootedStuff"] = "Geplünderte Gegenstände automatisch ausrüsten"
L["autoEquipSpecChangedStuff"] = "Automatisches ausrüsten beim Ändern der Spezialisierung"
L["AutoRepair"] = "Reparieren mit eigenen Geld"
L["auto-repair"] = "Repariere automatisch"
L["auto-repairDesc"] = "Aktiviert / deaktiviert die automatische Reparatur"
L["betterThanNothing"] = "Dieser Gegenstand ist besser als nichts"
L["CantRepair"] = "Du kannst nicht reparieren"
L["checkGHAutoTell"] = "Aktiviere / deaktiviere automatische Ankündigung im Raid"
L["customWeights"] = "Benutzerdefinierte Gewichtung"
L["DeactivatedRed"] = "|cFFFF0000Deaktiviert|r"
L["demande1"] = "Willst Du "
L["demande2"] = "fragen, ob er es benötigt"
L["DNR"] = "Nicht automatisch reparieren"
L["dot"] = "."
L["DropBy"] = "Fallen gelassen von:"
L["DropRate"] = "Plünderchance:"
L["DropZone"] = "Standort:"
L["enable"] = "Aktivieren"
L["equipVerbose"] = "wurde soeben von GearHelper ausgerüstet"
L["gearOptions"] = "Ausrüstungssoptionen"
L["getLoot"] = "erhält"
L["gold"] = "g"
L["GuildAutoRepair"] = "Reparieren mit Gildengold"
L["guildRepairCost"] = "Gildenreparaturkosten:"
L["helpConfig"] = "config - Öffnet das Konfigurationsfenster"
L["helpCW"] = "cw - Öffnet das Benutzerdefinierte Gewichtungsfenster"
L["helpDebug"] = "debug - Aktiviert den Debugmodus"
L["helpVersion"] = "version - Zeigt die aktuelle Version von GH an"
L["ilvlInspect"] = "Durchschnittliches ilvl:"
L["InviteMessage"] = "Die Nachricht die geflüstert werden müssen für die automatische Einladung lautet:"
L["isAlive"] = "ist Lebendig!"
L["isDead"] = "ist tot!"
L["itemBetterThan"] = "|cFF7FFFD4Dieser Gegenstand ist besser als dein"
L["itemBetterThan2"] = "mit einem Wert von +"
L["itemBetterThanGeneral"] = "|cFF7FFFD4Dieser Gegenstand ist besser als deiner mit einem Wert von +"
L["itemEgal"] = "Dieser Gegenstand ist gleichwertig mit deinem"
L["itemEgala"] = "Dieser Gegenstand ist gleichwertig mit"
L["itemEgalMainD"] = "Dieser Gegenstand ist gleichwertig mit deiner Haupthand"
L["itemEgalMainG"] = "Dieser Gegenstand ist gleich gut wie deiner Linken Hand"
L["itemEquipped"] = "Ist aktuell ausgerüstet."
L["itemLessThan"] = "|cFFFF0066Dieser Gegenstand ist schlechter als dein"
L["itemLessThanGeneral"] = "|cFFFF0066Dieser Gegenstand ist schlechter als deiner"
L["itemNotEquippable"] = "Dieser Gegenstand ist nicht ausrüstbar"
L["lfrCheckButtonText"] = "Bereitschaftscheck automatisch akzeptieren"
L["lfrCheckButtonTooltip"] = "Aktiviere diese Box, um Bereitschaftschecks im LFR automatisch zu akzeptieren"
L["lootInRaidAlert"] = "Warne, wenn etwas besser ist"
L["mainD"] = "Rechte Hand"
L["mainG"] = "Linke Hand"
L["maj1"] = "Du benutzt Version |cFFFF0000"
L["maj2"] = "|r von GearHelper. Version |cFF00FF00"
L["maj3"] = "|r wurde gefunden von"
L["maLangue"] = "Deutsch "
L["maLanguedeDE"] = "Deutsch"
L["maLangueenUS"] = "German"
L["maLangueesES"] = "Alemán"
L["maLangueesEX"] = "Alemán"
L["maLanguefrFR"] = "Allemand"
L["maLangueitIT"] = "Tedesco"
L["maLanguekoKR"] = "독일의"
L["maLangueptBR"] = "Alemão"
L["maLangueruRU"] = "немецкий"
L["maLanguezhCN"] = "德国"
L["maLanguezhTW"] = "德國"
L["miscOptions"] = "Diverse Optionen"
L["MmTtClickLock"] = "Umschalt + Klick, um das Minimap Icon zu  |cFFFF0000fixieren|cFFFFFF00"
L["MmTtClickUnlock"] = "Umschalt + Klick, um das Minimap Icon |cFFFF0000freizugeben|cFFFFFF00"
L["MmTtCtrlClick"] = "Strg + Klick, um das Minimap Icon zu  |cFFFF0000verstecken|cFFFFFF00"
L["MmTtLClick"] = "Links-Klick zum Öffnen der Optionen"
L["MmTtRClickActivate"] = "Rechts-Klick zum Einschalten von GearHelper"
L["MmTtRClickDeactivate"] = "Rechts-Klick zum Ausschalten von GearHelper"
L["moneyEarned"] = "Geld verdient durch Verkauf:"
L["no"] = "Nein"
L["noxxicWeights"] = "Noxxic Gewichtungen"
L["questRewars"] = "Automatische Annahme von Questbelohnungen"
L["remove"] = "Entfernen"
L["repairCost"] = "Reparaturkosten:"
L["secondaryOptions"] = "Zusätzliche Optionen"
L["sellGrey"] = "Verkaufe graue Gegenstände"
L["slashCommandConfig"] = "config - Öffne das Optionenfenster"
L["slashCommandCw"] = "cw - Öffnen das benutzerdefinierte Gewichtungsfenster"
L["slashCommandVersion"] = "version - Zeigt die Addon Version an"
L["thanksPanel"] = "Vielen dank!"
L["UIautoInvite"] = "Einladung durch Flüstern"
L["UIBossesKilled"] = "Bosse getötet"
L["UIBossesKilledDesc"] = "Zeige getötete Bosse im LFG Fenster"
L["UICWasPercentage"] = "Wert in Prozent"
L["UICWasPercentageDescription"] = "Beschreiben die Bedeutung jeder Statistik durch eine Zahl, die einen Prozentsatz darstellt, die Summe der Werte muss 100 sein."
L["UIcwGemSocketCompute"] = "Berücksichtige leere Sockets in der Berechnung"
L["UIcwIlvlOption"] = "Berücksichtige iLvl in der Berechnung"
L["UIcwIlvlWeight"] = "iLvl Gewichtung"
L["UIcwTemplateToUse"] = "Zu verwendende Vorlage"
L["UIGHCheckBoxAddon"] = "Schalte GearHelper ein/aus"
L["UIGHCheckBoxAutoAcceptQuestReward"] = "Schalte automatisches Akzeptieren von Questbelohnungen ein/aus"
L["UIGHCheckBoxAutoEquipLootedStuff"] = "Schalte automatisches Ausrüsten geplünderter Gegenstände ein/aus"
L["UIGHCheckBoxAutoEquipWhenSwitchSpe"] = "Aktiviere / deaktiviere automatisches Ausrüsten beim wechseln der Spezialisierung"
L["UIGHCheckBoxAutoInvite"] = "Automatisches Einladen der Person, welche dir den text zuflüstert |cFF00FF00"
L["UIGHCheckBoxlootInRaidAlert"] = "Schalte die Option ein/aus, um darüber informiert zu werden, wenn jemand eine bessere Ausrüstung als deine aktuelle plündert."
L["UIGHCheckBoxSellGrey"] = "Schalte automatisches Verkaufen von grauen Gegenständen ein/aus"
L["UIGlobalComputeNotEquippable"] = "Zeige nicht ausrüstbare Gegenstände"
L["UIGlobalComputeNotEquippableDescription"] = 'Zeige "Dieser Gegenstand ist schlechter als deiner" bei nicht-ausgerüsteten Gegenständen'
L["UIIlvlCharFrame"] = "ilvl Charakterfenster"
L["UIIlvlCharFrameDesc"] = "Zeige das ilvl deiner Gegenstände im Charakterfenster"
L["UIIlvlInspectFrame"] = "ilvl beim betrachten"
L["UIIlvlInspectFrameDesc"] = "Zeigt das iLvl Ihres Ziels beim betrachten an"
L["UIinviteMessage"] = "Einladungsnachricht"
L["UIinviteMessageDesc"] = "Einladungsnachricht, die dir gesendet werden muss, um eingeladen zu werden"
L["UIMinimapIcon"] = "Minimap Icon"
L["UIMinimapIconDesc"] = "Zeige das Minimap Icon"
L["UIMyNames"] = "Namen"
L["UIMyNamesDesc"] = "Namen für die Warnungen. Getrennt durch Kommata (keine Leerzeichen)"
L["UIprintWhenEquip"] = "Nachricht beim automatischen ausrüsten"
L["UISayMyName"] = "Sag meinen Namen"
L["UISayMyNameDesc"] = "Zeige eine Warnung mit Ton, wenn jemand deinen Namen schreibt"
L["UIstatsTemplateToUse"] = "Zu verwendende Statistik Vorlage"
L["UItemplateName"] = "Neue Vorlage"
L["UIWhisperAlert"] = "Flüster Alarm"
L["UIWhisperAlertDesc"] = "Spiele einen Ton, wenn du angeflüstert wirst"
L["yes"] = "Ja"
-------------------------- CE QUI EST EN DESSOUS DE CETTE LIGNE N'EST PAS DISPO SUR CURSE ----------------------------

------------------------------------------------ SUPRIMER CETTE LIGNE ------------------------------------------------
-----

L["Tooltip"] = {
    Stat = {
        ["Intellect"] = ITEM_MOD_INTELLECT_SHORT,
        ["Haste"] = ITEM_MOD_HASTE_RATING_SHORT,
        ["CriticalStrike"] = ITEM_MOD_CRIT_RATING_SHORT,
        ["Versatility"] = ITEM_MOD_VERSATILITY,
        ["Mastery"] = ITEM_MOD_MASTERY_RATING_SHORT,
        ["Agility"] = ITEM_MOD_AGILITY_SHORT,
        ["Stamina"] = ITEM_MOD_STAMINA_SHORT,
        ["Strength"] = ITEM_MOD_STRENGTH_SHORT,
        ["Armor"] = RESISTANCE0_NAME,
        ["Multistrike"] = ITEM_MOD_CR_MULTISTRIKE_SHORT,
        ["DPS"] = ITEM_MOD_DAMAGE_PER_SECOND_SHORT,
        ["Leech"] = "Lebensraub",
        ["Avoidance"] = "Vermeidung",
        ["MovementSpeed"] = "Bewegungsgeschwindigkeit"
    },
    ["ItemLevel"] = "^Gegenstandsstufe",
    ["LevelRequired"] = "^Benötigt Stufe",
    ["GemSocketEmpty"] = "Sockel",
    ["BonusGem"] = "^Sockelbonus"
    --["MainDroite"] = "Dégâts main droite",
    --["MainGauche"] = "Dégâts main gauche"
}
