local L = LibStub("AceLocale-3.0"):NewLocale("GearHelper", "ruRU")
if not L then
    return
end

L["merci"] = "|cFF00FF00Спасибо персонажу |cFF00BFFFЭэтанолл-РевущийФьорд|cFF00FF00 фьорд за помощь с русской локализацией."

L["local"] = "RU"
L["Addon"] = "|cFF00FF00GearHelper : |r"
L["helpHelpInfo"] = "|cFFFFFF00Type |cFF00FF00/gh help|r|cFFFFFF00 to show help|r" --    you can change if you keep "/gh help"
L["stateHelpInfo"] = "|cFFFFFF00/gh state to show |cFF00FF00GearHelper|r's help" --    same but keep  "/gh state"
L["configHelpInfo"] = "|cFFFFFF00/gh or /gh config to configure |cFF00FF00GearHelper" --	  same but keep "/gh" and "/gh config"
L["SellGrey"] = "Авто продажа серых вещей : "
L["ActivatedGreen"] = "|cFF00FF00включено|r"
L["DeactivatedRed"] = "|cFFFF0000выключено|r"
L["addonActivated"] = "|cFF00FF00GearHelper |cFFFFFF00is|r включено|r" --   You forgot "is" ^^
L["sellGreyActivated"] = "Авто продажа серых вещей|cFF00FF00 включена|r"
L["AutoGreed"] = "Авто НЕ ОТКАЖУСЬ от вещей на ваш спек : "
L["AutoAcceptQuestReward"] = "Авто принятие награды за квест : "
L["AutoNeed"] = "Авто НУЖНО, если лут лучше чем вещь сейчас у вас : "
L["AutoEquipLootedStuff"] = "Авто одевание лута : "
L["AutoEquipWhenSwitchSpe"] = "Авто смена вещей при смене специализации : "
L["itemLessThan"] = "|cFFFF0066Эта вещь хуже чем у вас"
L["itemLessThanGeneral"] = "|cFFFF0066Эта вещь хуже чем ваша"
L["itemBetterThan"] = "|cFF7FFFD4Эта вещь лучже чем ваша"
L["itemBetterThan2"] = "лучше на +"
L["itemBetterThanGeneral"] = "|cFF7FFFD4Эта вещь лучже чем ваша на +"
L["slashCmdInfo"] = "|cFFFFFF00Type |cFF00FF00/gh|r|cFFFFFF00 or |cFF00FF00/gh help|r|cFFFFFF00 показать помощь|r" -- just keep "/gh" and "/gh help"
L["iNeededOn"] = "Мне НУЖНО включено  "
L["UIGHCheckBoxAddon"] = "Включить GearHelper"
L["UIGHCheckBoxSellGrey"] = "Включить Авто продажу серых вещей"
L["UIGHCheckBoxAutoGreed"] = "Включить Авто НЕ ОТКАЖУСЬ от вещей на ваш спек"
L["UIGHCheckBoxAutoAcceptQuestReward"] = "Включить Авто принятие награды за квест"
L["UIGHCheckBoxAutoNeed"] = "Включить Авто НУЖНО, если лут лучше чем вещь сейчас у вас"
L["UIGHCheckBoxAutoEquipLootedStuff"] = "Включить Авто одевание лута"
L["UIGHCheckBoxAutoEquipWhenSwitchSpe"] = "Включить Авто смена вещей при смене специализации"
L["radioAMRButton"] = "Ask Mr Robot"
L["radioNoxxicButton"] = "Noxxic"
L["reliqueAP"] = "Реликвия для Артефакта"
L["version1"] = "Вы используете версию |cFFFF0000"
L["version2"] = "|r of GearHelper. Версия |cFF00FF00" --  this is use for   "you are using ... version OF GearHelper"    you can translate if you want
L["version3"] = "|r было найдено в "
L["version4"] = " (Curse)"
L["state1"] = "|cFFFFFF00GearHelper - "
L["state2"] = "|cFFFFFF00, Авто продажа серых вещей - "
L["state3"] = "|cFFFFFF00, Авто НЕ ОТКАЖУСЬ - "
L["state4"] = "|cFFFFFF00, Авто принятие награды за квестn - "
L["state5"] = "|cFFFFFF00, Авто НУЖНО, если лут лучше чем вещь сейчас у вас - "
L["state6"] = "|cFFFFFF00, Авто одевание лута - "
L["state7"] = "|cFFFFFF00, Авто смена вещей при смене специализации - "
L["stateError"] = "Ошибка с /gh state. Пожалуйств напишите мне на мыло @ marsgames@gmail.com"
L["mmButton"] = "Включить кнопку у мини-карты"
L["RepairWithOwnGold"] = "Авто починка : "
L["RepairWithGuildGold"] = "Авто починка за счёт гильдии : "
L["CantRepair"] = "Вы не можете починиться"
L["repairCost"] = "Починка стоила : "
L["guildRepairCost"] = "Гильдия оплатила починку : "
L["gold"] = "g" -- g for gold (in english)  / po for piece d'or (in french)...
L["dot"] = "."
L["DNR"] = "Не чинить вещи автоматически"
L["AutoRepair"] = "Чинить вещи автоматически"
L["GuildAutoRepair"] = "Чинить вещи за счёт гильдии, если это возможно"
L["itemEgal"] = "Эта вещь равна вашей"
L["itemEgala"] = "Эта вещь равна  "
L["itemEgalMainD"] = "Это оружие равно вашему в Правой Руке"
L["itemEgalMainG"] = "Это оружие равно вашему в Левой Руке"
L["mainD"] = " Правая Рука "
L["mainG"] = " Левая Рука "
L["UIGHCheckBoxAutoInvite"] = "Автоматически пригласить персонажа который написал вам /ш ваш текст       |cFF00FF00 "
L["AutoInvite"] = "Авто приглашение после шёпота : "
L["state8"] = "|cFFFFFF00 авто приглашение после шёпота - "
L["state9"] = "|cFFFFFF00, авто сообщение о луте - "
L["checkGHAutoTell"] = "Включить авто сообщение о луте в рейд"
L["ghversion"] = "|cFFFFFF00/gh version чтобы увидеть версию аддона"
L["ghim"] = '|cFFFFFF00/gh im "сообщение" замените сообщение на что-нибудь, чтобы шепчущий Вам автоматически пригласился в группу на "сообщение"'
L["InviteMessage"] = "Сообщение того, чтобы шепчущий Вам автоматически пригласился в группу : "
L["AutoTell"] = "Автоматически объявлять лут если Вы в рейде и являетесь рейд лидером - "
L["radioIcyVeinsButton"] = "Custom Weights"
L["ivIndisponible"] = "BETA TEST : It is not recommanded to use this function"
L["moneyEarned"] = "Money earned by selling : "
L["ask1"] = "|FFFFFF00You can ask "
L["ask2"] = "|FFFFFF00 if he needs "
L["demande1"] = "Do you want to ask to "
L["demande2"] = " if he needs "
L["yes"] = "Yes"
L["no"] = "No"
L["demande4ruRU"] = "[GearHelper] - Hey, I would like to know if you need your "
L["UIGHCheckBoxAskLootRaid"] = "Enable / disable option to tell you if someone loot something better in instance"
L["AskLootRaid"] = "Option to tell you if someone loot something better than what you have equipped is : "
L["maj1"] = "You are using version |cFFFF0000"
L["maj2"] = "|r of GearHelper. Version |cFF00FF00"
L["maj3"] = "|r was find from "
L["equipVerbose"] = " has just been equipped by GearHelper"
L["PrintWhenEquip"] = "Option to print out in chat when something is automatically equipped by GearHelper is : "
L["helpGHRam"] = "|cFFFFFF00/gh ram to show how many ram is used by GearHelper"
L["maLangue"] = "russian"

L["Tooltip"] = {
    Stat = {
        ["Intellect"] = ITEM_MOD_INTELLECT_SHORT,
        ["Haste"] = ITEM_MOD_HASTE_RATING_SHORT,
        ["CriticalStrike"] = ITEM_MOD_CRIT_RATING_SHORT,
        ["Versatility"] = ITEM_MOD_VERSATILITY,
        ["Mastery"] = ITEM_MOD_MASTERY_RATING_SHORT,
        ["Agility"] = ITEM_MOD_AGILITY_SHORT,
        ["Stamina"] = ITEM_MOD_STAMINA_SHORT,
        ["Strength"] = ITEM_MOD_STRENGTH_SHORT,
        ["Armor"] = RESISTANCE0_NAME,
        ["Multistrike"] = ITEM_MOD_CR_MULTISTRIKE_SHORT,
        ["DPS"] = ITEM_MOD_DAMAGE_PER_SECOND_SHORT,
        ["Leech"] = "самоисцелению",
        ["Avoidance"] = "к избеганию",
        ["MovementSpeed"] = "к скорости передвижения"
    },
    ["ItemLevel"] = "^Уровень предмета",
    ["LevelRequired"] = "^Требуется уровень",
    ["GemSocketEmpty"] = "Гнезда",
    ["BonusGem"] = "^Бонусы от камней"
    --["MainDroite"] = "Dégâts main droite",
    --["MainGauche"] = "Dégâts main gauche"
}
