local L = LibStub("AceLocale-3.0"):NewLocale("GearHelper", "zhCN")
if not L then
	return
end

L["merci"] = "Thanks to yusen for the translation"
L["local"] = "CN"

-------------------------- CE QUI EST EN DDESSOUS DE CETTE LIGNE N'EST PAS DISPO SUR CURSE --------------------------
L["ActivatedGreen"] = "| cFF00FF00已启用 | R"
L["Addon"] = "|cFF00FF00GearHelper 是 : "
L["ask1"] = "|cFFFFFF00你可以问 ["
L["ask2"] = "|cFFFFFF00] 如果他需要的话"
L["autoEquipLootedStuff"] = "自动装备拾取的战利品"
L["autoEquipSpecChangedStuff"] = "切换天赋时自动装备"
L["autoGreed"] = "自动贪婪"
L["autoNeed"] = "自动需求"
L["AutoRepair"] = "自费修理"
L["auto-repair"] = "自动修理"
L["auto-repairDesc"] = "启用/禁用 自动修理"
L["betterThanNothing"] = "有这个物品总比没有好"
L["CantRepair"] = "你无法修理"
L["checkGHAutoTell"] = "在raid中 启用/禁用 自动通告战利品"
L["customWeights"] = "自定义权重"
L["DeactivatedRed"] = "|cFFFF0000已停用|r"
L["demande1"] = "你想要问"
L["demande2"] = "如果他需要的话"
L["DNR"] = "不自动修理"
L["dot"] = "。"
L["DropBy"] = "掉落自："
L["DropRate"] = "掉落概率："
L["DropZone"] = "地点："
L["enable"] = "启用"
L["equipVerbose"] = "现已配置好GearHelper"
L["gearOptions"] = "Gear工具 选项"
L["getLoot"] = "收到"
L["gold"] = "G"
L["GuildAutoRepair"] = "使用公会自动修理"
L["guildRepairCost"] = "公会修理费："
L["ilvlInspect"] = "平均物品等级："
L["iNeededOn"] = "我选择需求了"
L["InviteMessage"] = "向您发送自动密语消息的是："
L["itemBetterThan"] = "|cFF7FFFD4此物品比你的更好"
L["itemBetterThan2"] = "提高值 +"
L["itemBetterThanGeneral"] = "|cFF7FFFD4此物品比你的更好，提高值  +"
L["itemEgal"] = "此物品与你的装等相同"
L["itemEgala"] = "物品装等相同"
L["itemEgalMainD"] = "此物品与你的副手等级相同"
L["itemEgalMainG"] = "此物品与你的主手等级相同"
L["itemEquipped"] = "此物品已装备"
L["itemLessThan"] = "|cFFFF0066此装备比你的差"
L["itemLessThanGeneral"] = "|cFFFF0066此装备和你的相比一般"
L["lootInRaidAlert"] = "如果掉落的物品更好在团队警告窗口中发出提示"
L["mainD"] = "副手"
L["mainG"] = "主手"
L["maj1"] = "你正在使用的版本 |cFFFF0000"
L["maj2"] = "|r 最新GearHelper的. 版本 |cFF00FF00"
L["maj3"] = "|r 从中搜索"
L["maLangue"] = "英语。"
L["maLanguedeDE"] = "德语。"
L["maLangueenUS"] = "美式英语。"
L["maLangueesES"] = "西班牙语。"
L["maLangueesEX"] = "拉丁美洲西班牙语。"
L["maLanguefrFR"] = "法语。"
L["maLangueitIT"] = "意大利语。"
L["maLanguekoKR"] = "韩语。"
L["maLangueptBR"] = "葡萄牙语。"
L["maLangueruRU"] = "俄语。"
L["maLanguezhCN"] = "简体中文。"
L["maLanguezhTW"] = "繁体中文。"
L["miscOptions"] = "其它选项"
L["MmTtClickLock"] = "Shift + 鼠标点击 |cFFFF0000锁定|cFFFFFF00 小地图图标"
L["MmTtClickUnlock"] = "Shift +鼠标点击 |cFF00FF00解锁|cFFFFFF00小地图图标"
L["MmTtCtrlClick"] = "Ctrl +鼠标点击 |cFF00FF00隐藏|cFFFFFF00 小地图图标"
L["MmTtLClick"] = "左键单击打开选项"
L["MmTtRClickActivate"] = "右键单击启用GearHelper"
L["MmTtRClickDeactivate"] = "右键单击停用GearHelper"
L["moneyEarned"] = "出售赚取的钱："
L["no"] = "No.不是"
L["noxxicWeights"] = "Noxxic权重（Noxxic是国外的一个PvE/PvP全职业指导站，属性优先级来源是SimC，FemaleDwarf和论坛讨论。）"
L["questRewars"] = "自动接受任务奖励"
L["remove"] = "移动"
L["repairCost"] = "修理费："
L["sellGrey"] = "出售灰色物品"
L["UIautoInvite"] = "自动组队密语邀请"
L["UIBossesKilled"] = "首领已击杀"
L["UIBossesKilledDesc"] = "在LFG组队面板上显示首领已击杀"
L["UICWasPercentage"] = "百分比值"
L["UICWasPercentageDescription"] = "用百分比数字显示每个统计数据的重要性，该值的总和必须为100"
L["UIcwGemSocketCompute"] = "镶孔奖励放入计算中"
L["UIcwIlvlOption"] = "物品等级放入计算中"
L["UIcwIlvlWeight"] = "物品等级权重"
L["UIcwTemplateToUse"] = "使用模版"
L["UIGHCheckBoxAddon"] = "启用 / 禁用 GearHelper"
L["UIGHCheckBoxAutoAcceptQuestReward"] = "启用/禁用 自动接受任务奖励"
L["UIGHCheckBoxAutoEquipLootedStuff"] = "拾取战利品后 启用/禁用 自动装备"
L["UIGHCheckBoxAutoEquipWhenSwitchSpe"] = "切换天赋时 启用/禁用 自动装备"
L["UIGHCheckBoxAutoGreed"] = "副本中 启用/禁用 自动贪婪。"
L["UIGHCheckBoxAutoInvite"] = "自动组队邀请用语 /w 文字编辑        |cFF00FF00"
L["UIGHCheckBoxAutoNeed"] = "副本中 启用/禁用 自动需求"
L["UIGHCheckBoxlootInRaidAlert"] = "启用/禁用选项，以便在有人拾取了比你装备的东西更好时通知你"
L["UIGHCheckBoxSellGrey"] = "启用/禁用 自动销售灰色物品"
L["UIGlobalComputeNotEquippable"] = "显示不可装备的物品"
L["UIGlobalComputeNotEquippableDescription"] = "在不可装备的物品上显示“此物品比你的物品差”"
L["UIIlvlCharFrame"] = "物品等级字符框面板"
L["UIIlvlCharFrameDesc"] = "在字符框面板上显示物品的ilvl等级"
L["UIIlvlInspectFrame"] = "观察面板ilvl装等"
L["UIIlvlInspectFrameDesc"] = "观察时显示你目标的ilvl装等"
L["UIinviteMessage"] = "组队邀请消息"
L["UIinviteMessageDesc"] = "组队邀请消息是通知你是否被邀请。"
L["UIMinimapIcon"] = "小地图图标"
L["UIMinimapIconDesc"] = "在小地图上显示图标"
L["UIMyNames"] = "名称"
L["UIMyNamesDesc"] = "提醒的名称列表。 用逗号分隔（无空格）"
L["UIprintWhenEquip"] = "自动装备时发布"
L["UISayMyName"] = "说出我的名字"
L["UISayMyNameDesc"] = "当有人通过你的名字联络你时，显示和声音提醒"
L["UIstatsTemplateToUse"] = "使用统计模版"
L["UItemplateName"] = "新模板"
L["UIWhisperAlert"] = "密语提醒"
L["UIWhisperAlertDesc"] = "当你密语时播放声音。"
L["yes"] = "Yes.是的"

-------------------------- CE QUI EST EN DESSOUS DE CETTE LIGNE N'EST PAS DISPO SUR CURSE --------------------------

------------------------------------------------ SUPRIMER CETTE LIGNE ------------------------------------------------
-----

L["Tooltip"] = {
	Stat = {
		["Intellect"] = ITEM_MOD_INTELLECT_SHORT,
		["Haste"] = ITEM_MOD_HASTE_RATING_SHORT,
		["CriticalStrike"] = ITEM_MOD_CRIT_RATING_SHORT,
		["Versatility"] = ITEM_MOD_VERSATILITY,
		["Mastery"] = ITEM_MOD_MASTERY_RATING_SHORT,
		["Agility"] = ITEM_MOD_AGILITY_SHORT,
		["Stamina"] = ITEM_MOD_STAMINA_SHORT,
		["Strength"] = ITEM_MOD_STRENGTH_SHORT,
		["Armor"] = RESISTANCE0_NAME,
		["Multistrike"] = ITEM_MOD_CR_MULTISTRIKE_SHORT,
		["DPS"] = ITEM_MOD_DAMAGE_PER_SECOND_SHORT,
		["Leech"] = "吸血",
		["Avoidance"] = "闪避",
		["MovementSpeed"] = "加速"
	},
	["ItemLevel"] = "^物品等级",
	["LevelRequired"] = "^需要等级",
	["GemSocketEmpty"] = "插槽",
	["BonusGem"] = "^镶孔奖励"
	--["MainDroite"] = "Dégâts main droite",
	--["MainGauche"] = "Dégâts main gauche"
}
