name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upload to CurseForge
        run: python curseforge_uploader.py --tag ${{ github.ref_name }}
        env:
          CF_PUBLIC_API_TOKEN: ${{ secrets.CF_API_KEY }}
